### PR TITLE
[IMP] Add first setup file

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Comment by rousseldenis** [comment]
And a first .gitignore file

**Comment by eturpault** [comment]
Hello @rousseldenis, the setup.py file that you are proposing is to be used with pyinstaller to generate an executable of the OdfEdit tool, is it correct ?
What is the goal of the file .gitignore ?

**Comment by rousseldenis** [comment]
> Hello @rousseldenis, the setup.py file that you are proposing is to be used with pyinstaller to generate an executable of the OdfEdit tool, is it correct ?

Yes. But that's also true to install for instance the tool in a virtualenv with pip.

That can help, in fact, more globally to package the tool (for linux, windows, ...), do the tests, ...

> What is the goal of the file .gitignore ?

.gitignore file is describing what ... ignoring when working with git. Typically, build files, temporary files, and so on. Which files typically we don't want to appear here.

**Comment by eturpault** [comment]
@rousseldenis I let you manage these setup.py and .gitignore files if you think they can be usefull, personnaly I don't know how to use it. I would limit my contribution to this repo in providing updates of the OdfEdit tool (source code and executable binaries for Windows and Linux). Thanks anyway for trying to improve the integration of OdfEdit in this repo !

**Comment by rousseldenis** [comment]
@eturpault This is a ready version.

With this, you can do :

- Create a virtualenv
- `pip install -r requirements.txt`
- `pip install .`

and that's it for development.

As said there https://github.com/GrandOrgue/ODFEdit/discussions/2#discussioncomment-4869991, you don't need to have one file per version. Git history will help.

IMHO, we can merge this. Then, I can look at automatic builds if you want as we release GrandOrgue executables.

**Comment by rousseldenis** [comment]
This will help also to push this to pypi.

https://pypi.org/

**Comment by rousseldenis** [comment]
@eturpault Do you have the entire pyinstaller command ? I'll try to write automatic builds

**Comment by eturpault** [comment]
@rousseldenis : here is the pyinstaller command that I use to generate OdfEdit executable : 
pyinstaller "D:\GoogleDrive\Python\OdfEdit\Source\OdfEdit.py" -F -w -y --clean --distpath "D:\GoogleDrive\Python\OdfEdit\pyinstaller\dist" --workpath "D:\GoogleDrive\Python\OdfEdit\pyinstaller\build" --icon="D:\GoogleDrive\Python\OdfEdit\Source\OdfEdit.ico" --add-data "D:\GoogleDrive\Python\OdfEdit\Source;."

About the virtual environment, pip install, pypi, and other stuff to facilitate the building and pushing of OdfEdit, I have not the time for the moment to work on using these tools, I prefer to dedicate time on OdfEdit improvement. If you want to do it by yourself you are welcome, thank you ! May be one day we could have a call together (I suppose that you speak French like me) so that you could explain me this tools environment (and the proper usage of GitHub as well :-) ).

**Comment by rousseldenis** [comment]
> @rousseldenis : here is the pyinstaller command that I use to generate OdfEdit executable :
> pyinstaller "D:\GoogleDrive\Python\OdfEdit\src\OdfEdit.py" -F -w -y --clean --distpath "D:\GoogleDrive\Python\OdfEdit\pyinstaller\dist" --workpath "D:\GoogleDrive\Python\OdfEdit\pyinstaller\build" --icon="D:\GoogleDrive\Python\OdfEdit\src\OdfEdit.ico" --add-data "D:\GoogleDrive\Python\OdfEdit\src;."

Great, thanks !



> About the virtual environment, pip install, pypi, and other stuff to facilitate the building and pushing of OdfEdit, I have not the time for the moment to work on using these tools, I prefer to dedicate time on OdfEdit improvement. If you want to do it by yourself you are welcome, thank you ! May be one day we could have a call together (I suppose that you speak French like me) so that you could explain me this tools environment (and the proper usage of GitHub as well :-) ).

No problem with that as you already said it. I wanted to inform you about the advantages of it.

**Comment by eturpault** [comment]
@rousseldenis : maybe this PR should be cancelled, isn't it ?

**Comment by rousseldenis** [comment]
Of course!

**Pull request closed without merging**
